language: node_js

if: tag IS present

node_js:
  - 9

cache:
  directories:
    - node_modules

deploy:
  - provider: npm
    email: laomao800@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: laomao800/vue-dropdown-selector

  - provider: pages
    local-dir: demo
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
